---
- name: Check if ~/bin exists
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/bin"
  register: bin_dir

- name: Create ~/bin if it doesn't exist
  ansible.builtin.file:
    path: "{{ bin_dir }}"
    state: directory
    mode: "0751"
  when: not bin_dir.stat.exists
