---
- name: Check if ~/bin exists
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/bin"
  register: macos_bindir

- name: Create ~/bin if it doesn't exist
  ansible.builtin.file:
    path: "{{ macos_bindir }}"
    state: directory
    mode: "0751"
  when: not macos_bindir.stat.exists
