---
- name: Install packages for OSD
  community.general.homebrew:
    name: "{{ packages }}"
    state: present
    update_homebrew: true

- name: Create ~/bin dir if it doesn't exist
  ansible.builtin.import_tasks:
    file: create_bin_dir.yml

- name: Install scripts
  ansible.builtin.file:
    src: "{{ role_path }}/files/scripts/{{ item }}.sh"
    dest: "{{ bin_dir.stat.path }}/{{ item }}"
    state: link
  loop: "{{ scripts }}"
